"""H53-1 · Cross-dataset **orientation coincidence** with a randomization null.

The hypothesis this implements
------------------------------
A fault trace is a *line* in several physically independent datasets at once.  The catalogue that the
competition scores against was built by manual interpretation (USGS Quaternary fault maps + the
INGENIOUS compilation), and every published note in this family agrees on the failure mode of
automatic mappers in this province: they fire on roads, canals, levees, canyon rims and stream banks
because those are linear in **one** dataset (topography) and nothing else (Hermant, Kiersnowski &
Bellanger 2025, 50th Stanford Geothermal Workshop, https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2025/Hermant.pdf ,
listed by the organisers on the competition's own About page as recommended reading).

So the discriminating question is not "is there a line here" -- a single view answers that, and the
0.2778 baseline file answers it 37,654 times -- but **"do independent physics agree that it is a
line, at this place, with this strike?"**  This module answers exactly that question and calibrates
"agree" against a randomization null instead of a hand-picked threshold.

What is measured, and what it is not
------------------------------------
Per dataset ``c`` the structure tensor (``gems52.structure``) gives an azimuth field.  At 1.6 km tiles
that field is reduced to a weighted axial mean azimuth with a concentration ``R``, and for a pair of
datasets ``(c, d)`` the coincidence statistic is

    obs(c,d) = mean over tiles of cos( 2 * (theta_c - theta_d) )        (null 0, see gems52.azimuth)

with the null distribution generated by **rolling one azimuth field across the tile grid** -- a
circular shift that preserves each field's own spatial structure and destroys only the pointwise
pairing.  That is the correct null for "these two fields agree at the same place": a null built from
shuffling individual tiles would inflate significance by breaking the autocorrelation that makes
neighbouring tiles identical.  ``p`` is the standard ``(1 + #{null >= obs}) / (1 + n_perm)``.

Two things this module deliberately does **not** do:

* It does not use any truth label.  The permutation test is unsupervised; nothing here is fitted to
  the catalogue, so a candidate it produces is not a copy of the catalogue by construction.
* It does not claim the datasets are independent in the statistical sense.  Magnetic and gravity
  grids share a processing heritage, and the "families" below (magnetics / gravity / radar /
  radiometric / topographic) are the *physics* level at which a coincidence is meaningful.  The
  requirement that agreement come from **different families** is what stops "two magnetic bands agree"
  from being counted twice; the number of families, not the number of files, is the sample size.

Data sources (all already in this repository, hash-pinned; see registry/data_manifest.json):
  * official competition cube ``data/training_features.tif``, 19 float32 bands, EPSG:32611 @ 100 m;
  * ``data/external/geodawn_rad_u8.tif``  -- GeoDAWN airborne gamma-ray spectrometry K, Th, U, TC
    (USGS GeoDAWN release; the competition's own About page points at GeoDAWN:
    https://www.sciencebase.gov/catalog/item/657e1d85d34e23d3533209f7 );
  * ``data/external/geodawn_extensions_u8.tif`` -- derived ternary ratios and an upward-continued TMI
    (``TMI_up150``), i.e. a depth-filtered magnetic grid that suppresses shallow sources.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import rasterio
from scipy import ndimage

from . import azimuth as A
from . import nodes as ND
from . import structure as S
from .transform import rank01 as T_rank01

PIXEL_M = 100.0
TILE_PX = 16                    # 16 px = 1.6 km square tiles


@dataclass(frozen=True)
class ChannelSpec:
    key: str
    path: str
    band: int
    family: str
    physical: str

    def label(self) -> str:
        return f"{self.key}[{self.family}]"


OFFICIAL = "data/training_features.tif"
RAD = "data/external/geodawn_rad_u8.tif"
EXT = "data/external/geodawn_extensions_u8.tif"

# Band indices are 1-based and were read from the file's own TIFF tags
# (evidence/band_inventory.json, written by scripts/prepare_data.py from the bytes).
CHANNELS: tuple[ChannelSpec, ...] = (
    ChannelSpec("mag_hg", OFFICIAL, 3, "magnetics",
                "Total magnetic intensity horizontal gradient - a derivative edge detector"),
    ChannelSpec("mag_tc", OFFICIAL, 6, "magnetics",
                "Tilt angle / total curvature - the organisers' own magnetic edge detector"),
    ChannelSpec("mag_rtp", OFFICIAL, 2, "magnetics",
                "Reduced-to-pole magnetic anomaly - the standard fault-mapping magnetic product"),
    ChannelSpec("mag_vg", OFFICIAL, 9, "magnetics",
                "Total magnetic intensity vertical gradient"),
    ChannelSpec("grav_hg", OFFICIAL, 18, "gravity",
                "Isostatic gravity anomaly horizontal gradient"),
    ChannelSpec("grav_vg", OFFICIAL, 11, "gravity",
                "Isostatic gravity anomaly vertical gradient"),
    ChannelSpec("grav_slope", OFFICIAL, 5, "gravity",
                "Isostatic gravity anomaly slope"),
    ChannelSpec("cond", OFFICIAL, 17, "conductivity",
                "Surface conductivity - a subsurface, hydrology-linked property"),
    ChannelSpec("tmi_up150", EXT, 4, "magnetics_up",
                "Upward-continued TMI (150 m): shallower sources attenuated, deeper ones kept"),
    ChannelSpec("rad_ThK", EXT, 1, "radiometric",
                "Airborne gamma-ray Th/K ratio - alteration/lithology contrast, not topography"),
    ChannelSpec("rad_UK", EXT, 2, "radiometric", "Airborne gamma-ray U/K ratio"),
    ChannelSpec("rad_K", RAD, 1, "radiometric", "Airborne gamma-ray potassium"),
    ChannelSpec("rad_Th", RAD, 2, "radiometric", "Airborne gamma-ray thorium"),
    ChannelSpec("rad_TC", RAD, 4, "radiometric", "Airborne gamma-ray total count"),
    ChannelSpec("det_elev_slope", OFFICIAL, 19, "surface",
                "Slope of detrended elevation - View B, the surface view"),
    ChannelSpec("det_elev", OFFICIAL, 12, "surface",
                "Detrended elevation - View B, the surface view"),
)

# "surface" is View B.  Everything else is View A (potential field + subsurface + the radar/radiometric
# external products).  The family field, not this set, decides which agreements are counted.
SURFACE_KEYS = ("det_elev_slope", "det_elev")


def footprint() -> np.ndarray:
    """The competition footprint, measured from the sample submission (finite = inside)."""
    with rasterio.open("data/sample_submission.tif") as ds:
        return np.isfinite(ds.read(1))


def catalogue() -> np.ndarray:
    with rasterio.open("data/labels.tif") as ds:
        return ds.read(1) == 1


def read_channel(spec: ChannelSpec, valid: np.ndarray) -> np.ndarray:
    with rasterio.open(spec.path) as ds:
        a = ds.read(spec.band).astype(np.float32)
    a[~np.isfinite(a)] = np.nan
    a[a < -1e38] = np.nan
    return np.where(valid, a, np.nan)


# ------------------------------------------------------------------------------------------------
# tile reduction
# ------------------------------------------------------------------------------------------------

def tile_index(shape: tuple[int, int], tile: int = TILE_PX) -> tuple[np.ndarray, np.ndarray, tuple[int, int]]:
    """Flat tile id per pixel, the row-of-tiles index, and the (n_rows, n_cols) tile grid shape."""
    h, w = shape
    tr = np.arange(h) // tile
    tc = np.arange(w) // tile
    n_cols = (w + tile - 1) // tile
    n_rows = (h + tile - 1) // tile
    return tr[:, None] * n_cols + tc[None, :], tr, (n_rows, n_cols)


def tile_azimuth(az: np.ndarray, weight: np.ndarray, tid: np.ndarray, n_tiles: int,
                 min_weight: float = 8.0) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Weighted axial mean azimuth per tile, its concentration R, and the weight mass.

    Returns ``(theta[tile] or NaN, R[tile], mass[tile])``.  A tile whose total weight is below
    ``min_weight`` has no azimuth: a 1.6 km tile with 8 coherent pixels is not evidence of anything,
    and leaving it NaN is what keeps the permutation test honest about the number of usable tiles.
    """
    z2 = 2.0 * az
    ok = np.isfinite(z2) & np.isfinite(weight) & (weight > 0)
    c = np.where(ok, weight * np.cos(z2), 0.0)
    s = np.where(ok, weight * np.sin(z2), 0.0)
    wsum = np.where(ok, weight, 0.0)
    flat = tid.ravel()
    nc = np.bincount(flat[ok.ravel()], weights=c.ravel()[ok.ravel()], minlength=n_tiles)
    ns = np.bincount(flat[ok.ravel()], weights=s.ravel()[ok.ravel()], minlength=n_tiles)
    nm = np.bincount(flat[ok.ravel()], weights=wsum.ravel()[ok.ravel()], minlength=n_tiles)
    theta = np.full(n_tiles, np.nan)
    r = np.zeros(n_tiles)
    good = nm >= min_weight
    theta[good] = np.mod(0.5 * np.arctan2(ns[good], nc[good]), np.pi)
    r[good] = np.hypot(nc[good], ns[good]) / np.maximum(nm[good], 1e-12)
    return theta, r, nm


def coincidence_test(theta_a: np.ndarray, theta_b: np.ndarray, tile_shape: tuple[int, int],
                     n_perm: int = 400, seed: int = 0) -> tuple[dict, np.ndarray]:
    """Permutation test for "do these two azimuth fields agree at the same place?".

    The null rolls field ``b`` across the **tile grid** by a random offset: each field keeps its own
    spatial structure (autocorrelation, patchiness, gaps) and only the pointwise pairing is destroyed.
    That is the correct null for a same-place question; shuffling tiles individually would instead
    break the autocorrelation that makes neighbouring tiles near-identical, and would manufacture
    significance out of nothing.

    Two implementation facts that were bugs first and are now contract:

    * **The usable set is recomputed for every draw.**  Rolling ``b`` moves its NaN tiles around, so a
      draw's statistic must be taken over the tiles where *that draw's* rotated field is finite.  Using
      the observed trial's mask instead leaves NaN in the null and produced ``null_mean = nan`` -- and
      a z-score of NaN would have silently disabled every significance gate downstream.
    * **``null_mean``/``null_sd`` are computed over the finite draws only**, and the number of dropped
      draws is reported rather than hidden.

    Returns ``(summary, z_tile)`` where ``z_tile`` is a per-tile z-score of the observed agreement
    against the pooled per-tile null distribution (NaN where either field has no azimuth).  ``z_tile``
    is what makes the test usable *locally* -- a global p-value says "these two grids are related",
    while the local decision ("is the agreement at this tile unusual") needs the per-tile null.
    """
    if theta_a.shape != theta_b.shape:
        raise ValueError("tile grids must have the same shape")
    a = np.asarray(theta_a, dtype=np.float64).reshape(tile_shape)
    b = np.asarray(theta_b, dtype=np.float64).reshape(tile_shape)
    fin_a = np.isfinite(a)
    fin_b = np.isfinite(b)
    ok0 = fin_a & fin_b
    n_use = int(ok0.sum())
    if n_use < 12:
        return ({"obs": float("nan"), "p": float("nan"), "z": float("nan"), "n_tiles": n_use,
                 "n_perm": n_perm, "usable": False}, np.full(tile_shape, np.nan),
                np.full(tile_shape, np.nan))
    obs = float(np.mean(np.cos(2.0 * A.axial_difference(a[ok0], b[ok0]))))
    rng = np.random.default_rng(seed)
    h, w = tile_shape
    null = np.full(n_perm, np.nan)
    pooled_sum = np.zeros(tile_shape)
    pooled_sq = np.zeros(tile_shape)
    pooled_cnt = np.zeros(tile_shape)
    ns = []
    for i in range(n_perm):
        dy, dx = int(rng.integers(h)), int(rng.integers(w))
        br = np.roll(np.roll(b, dy, axis=0), dx, axis=1)
        okp = fin_a & np.isfinite(br)
        n = int(okp.sum())
        if n < 12:
            continue
        c2 = np.cos(2.0 * A.axial_difference(a[okp], br[okp]))
        null[i] = float(np.mean(c2))
        pooled_sum[okp] += c2
        pooled_sq[okp] += c2 * c2
        pooled_cnt[okp] += 1.0
        ns.append(n)
    good = np.isfinite(null)
    if good.sum() < 20:
        return ({"obs": obs, "p": float("nan"), "z": float("nan"), "n_tiles": n_use,
                 "n_perm": int(good.sum()), "usable": False}, np.full(tile_shape, np.nan),
                np.full(tile_shape, np.nan))
    nm = float(np.mean(null[good]))
    nsd = float(np.std(null[good]))
    ge = int((null[good] >= obs).sum())
    cnt = np.maximum(pooled_cnt, 1.0)
    tile_null_mean = np.where(pooled_cnt > 0, pooled_sum / cnt, np.nan)
    tile_null_var = np.where(pooled_cnt > 1, np.maximum(pooled_sq / cnt - tile_null_mean ** 2, 0.0),
                             np.nan)
    tile_sd = np.sqrt(tile_null_var)
    sel = pooled_cnt >= 30                     # a tile needs enough draws for a stable sd
    cos2_tile = np.where(ok0, np.cos(2.0 * A.axial_difference(a, b)), np.nan)
    with np.errstate(invalid="ignore", divide="ignore"):
        z_tile = np.where(ok0 & sel & (tile_sd > 1e-9),
                          (cos2_tile - tile_null_mean) / np.maximum(tile_sd, 1e-12), np.nan)
    summary = {"obs": obs, "p": (1.0 + ge) / (1.0 + int(good.sum())), "n_tiles": n_use,
               "n_perm": int(good.sum()), "null_mean": nm, "null_sd": nsd,
               "null_p95": float(np.percentile(null[good], 95)),
               "z": float((obs - nm) / max(nsd, 1e-12)) if nsd > 0 else float("nan"),
               "mean_tiles_per_draw": float(np.mean(ns)) if ns else float("nan"),
               "tiles_with_stable_tile_z": int((sel & ok0).sum()),
               "usable": True}
    # `cos2_tile` is returned alongside the z-map because a *distribution-free* gate is what the data
    # can actually support: a tile contributes one scalar, whose null s.d. is ~0.3, so |z| >= 3 would
    # require cos2 >= 0.9 and fires on 0.0 % of tiles -- a silently disabled gate.  The rank of a
    # tile's cos2 within its own pair's tile population needs no s.d. at all.
    return summary, z_tile, cos2_tile


# ------------------------------------------------------------------------------------------------
# the detector
# ------------------------------------------------------------------------------------------------

def _channel_lines(spec: ChannelSpec, valid: np.ndarray, sigma_tensor_m: float,
                   coh_gate: float, persist_gate: float, allowed: np.ndarray,
                   topk: int) -> dict:
    """One channel -> candidates, per-pixel line strength, and tile azimuths (pass 1 + pass 2).

    Returned arrays are either full-grid (``strength``, used once and dropped) or per-tile; the
    per-node extraction happens in :func:`build`, after the candidate union is known, so no per-channel
    full-grid arrays are ever held for more than one channel at a time.
    """
    a = read_channel(spec, valid)
    st = S.structure_tensor(a, valid, sigma_tensor_m=sigma_tensor_m)
    del a
    persist = S.oriented_line_energy(st["azimuth"], valid, sigma_m=sigma_tensor_m)
    coh = np.nan_to_num(st["coherence"], nan=0.0)
    per = np.nan_to_num(persist, nan=0.0)
    e_rank = np.nan_to_num(T_rank01(st["energy"], valid), nan=0.0).astype(np.float32)
    strength = (coh * per * e_rank).astype(np.float32)
    gate = allowed & (st["coherence"] > coh_gate) & (persist > persist_gate)
    cand = ND.local_maxima(np.where(gate, strength, 0.0), gate, radius_px=1)
    if int(cand.sum()) > topk:
        cand = ND.top_k_mask(strength, cand, topk)
    return {"cand": cand, "strength": strength, "coh": coh, "persist": per,
            "azimuth": st["azimuth"], "energy": st["energy"]}


def build_tiles(work_dir: str = "work/dicoincidence", sigma_tensor_m: float = 300.0,
                tile_px: int = TILE_PX, topk_per_channel: int = 60_000, coh_gate: float = 0.30,
                persist_gate: float = 0.35, log=print) -> dict:
    """Pass 1: candidates per channel + tile azimuths.  ~2 minutes, ~350 MB, writes tiles.npz.

    Staged on purpose: the permutation test and the arm rules are where the *thinking* changes and the
    tensors are where the *time* goes, so the expensive half is cached and only the cheap half re-runs
    when a statistic is corrected.  A single end-to-end function was rewritten five times in one
    session otherwise.
    """
    out = Path(work_dir)
    out.mkdir(parents=True, exist_ok=True)
    valid = footprint()
    cat = catalogue()
    allowed = valid & ~cat
    tid, _, tile_shape = tile_index(valid.shape, tile_px)
    n_tiles = int(tile_shape[0] * tile_shape[1])
    log(f"footprint {int(valid.sum())} px, catalogue {int(cat.sum())} px, "
        f"tiles {tile_shape[0]}x{tile_shape[1]} ({tile_px} px = {tile_px * PIXEL_M / 1000:.1f} km)")

    per_channel: dict[str, dict] = {}
    cand_union = np.zeros(valid.shape, dtype=bool)
    for spec in CHANNELS:
        d = _channel_lines(spec, valid, sigma_tensor_m, coh_gate, persist_gate, allowed,
                           topk_per_channel)
        n_cand = int(d["cand"].sum())
        cand_union |= d["cand"]
        theta_t, r_t, mass_t = tile_azimuth(d["azimuth"], d["coh"] * d["persist"], tid, n_tiles)
        per_channel[spec.key] = {"spec": spec, "theta": theta_t, "R": r_t, "mass": mass_t,
                                 "n_candidates": n_cand}
        log(f"  [pass 1] {spec.key:14s} family={spec.family:12s} candidates {n_cand:>7d}, "
            f"tiles with a resolvable azimuth {int(np.isfinite(theta_t).sum()):>6d}/{n_tiles}")
        del d
    log(f"candidate union: {int(cand_union.sum())} px")
    if not cand_union.any():
        raise RuntimeError("no candidates: thresholds are impossible on this data")
    np.savez_compressed(out / "tiles.npz",
                        tile_shape=np.array(tile_shape, dtype=np.int64),
                        candidate_px=np.array(cand_union.sum(), dtype=np.int64),
                        **{f"{k}__{f}": v for k, d in per_channel.items()
                           for f, v in (("theta", d["theta"]), ("R", d["R"]), ("mass", d["mass"]))},
                        **{f"ncand__{k}": np.array(d["n_candidates"], dtype=np.int64)
                           for k, d in per_channel.items()})
    return {"per_channel": per_channel, "tile_shape": tile_shape, "n_tiles": n_tiles,
            "cand_union": cand_union, "tile_px": tile_px, "sigma_tensor_m": sigma_tensor_m,
            "coh_gate": coh_gate, "persist_gate": persist_gate,
            "topk_per_channel": topk_per_channel}


def load_tiles(work_dir: str = "work/dicoincidence") -> dict:
    """Rebuild the pass-1 dict from ``tiles.npz`` without touching a raster."""
    z = np.load(Path(work_dir) / "tiles.npz")
    tile_shape = tuple(int(v) for v in z["tile_shape"])
    per_channel = {}
    for spec in CHANNELS:
        per_channel[spec.key] = {
            "spec": spec, "theta": z[f"{spec.key}__theta"], "R": z[f"{spec.key}__R"],
            "mass": z[f"{spec.key}__mass"], "n_candidates": int(z[f"ncand__{spec.key}"]),
        }
    return {"per_channel": per_channel, "tile_shape": tile_shape,
            "n_tiles": int(tile_shape[0] * tile_shape[1]),
            "candidate_px": int(z["candidate_px"]),
            "cand_union": None}


def agreement_percentile(cos2_tile: np.ndarray) -> np.ndarray:
    """Rank each tile's observed agreement within its own pair's tile population, in [0, 1].

    Distribution-free on purpose: it says "this tile agrees better than 90 % of the tiles this pair can
    be measured on", which needs no variance estimate and is therefore robust to the strong spatial
    autocorrelation that makes a per-tile z-score meaningless (neighbouring tiles are not independent
    samples of the same pair).
    """
    c = np.asarray(cos2_tile, dtype=np.float64)
    out = np.full(c.shape, np.nan)
    fin = np.isfinite(c)
    n = int(fin.sum())
    if n == 0:
        return out
    from scipy.stats import rankdata
    out[fin] = rankdata(c[fin], method="average") / n
    return out


def coincidence_table(tiles: dict, n_perm: int = 400, seed: int = 0, log=print) -> tuple[list, dict]:
    """Pass 2a: the family-disjoint permutation tests.  Cheap; re-run whenever a statistic changes."""
    per_channel = tiles["per_channel"]
    tile_shape = tiles["tile_shape"]
    keys = [c.key for c in CHANNELS]
    pairs, z_by_pair, pct_by_pair = [], {}, {}
    for i, ki in enumerate(keys):
        for kj in keys[i + 1:]:
            fi, fj = per_channel[ki]["spec"].family, per_channel[kj]["spec"].family
            if fi == fj:
                continue
            res, z_tile, cos2_tile = coincidence_test(per_channel[ki]["theta"],
                                                      per_channel[kj]["theta"],
                                                      tile_shape, n_perm=n_perm, seed=seed)
            if not res["usable"]:
                continue
            fin = np.isfinite(z_tile)
            res.update({"a": ki, "b": kj, "family_a": fi, "family_b": fj,
                        "tile_z_share_ge3": float((z_tile[fin] >= 3.0).mean()) if fin.any() else None,
                        "tile_z_share_le_m3": float((z_tile[fin] <= -3.0).mean()) if fin.any() else None})
            # flattened to the same row-major tile order tile_index() hands to the nodes; a 2-D map
            # indexed by a flat tile id silently reads the wrong tile (or raises) -- it raised.
            z_by_pair[(ki, kj)] = np.asarray(z_tile).reshape(-1)
            pct_by_pair[(ki, kj)] = agreement_percentile(cos2_tile).reshape(-1)
            pairs.append(res)
    pairs.sort(key=lambda r: r["p"])
    zt = z_threshold(len(pairs))
    if pairs:
        log(f"coincidence pairs tested: {len(pairs)} (family-disjoint); best: {pairs[0]['a']} vs "
            f"{pairs[0]['b']} obs {pairs[0]['obs']:+.3f}, null {pairs[0]['null_mean']:+.4f} "
            f"+- {pairs[0]['null_sd']:.4f}, z {pairs[0]['z']:+.1f}, p {pairs[0]['p']:.4f}")
    log(f"pairs clearing the Bonferroni z gate (|z| >= {zt:.2f}): "
        f"{sum(1 for p in pairs if p['z'] >= zt)} of {len(pairs)}")
    return pairs, {"z_gate": zt, "z_by_pair": z_by_pair, "pct_by_pair": pct_by_pair}


def build_nodes(tiles: dict, pairs: list, work_dir: str = "work/dicoincidence",
                n_perm: int = 400, seed: int = 0, log=print) -> dict:
    """Pass 2b: per-node evidence for every channel, written to nodes.npz."""
    out = Path(work_dir)
    valid = footprint()
    allowed = valid & ~catalogue()
    sigma_tensor_m = tiles.get("sigma_tensor_m", 300.0)
    coh_gate, persist_gate = tiles.get("coh_gate", 0.30), tiles.get("persist_gate", 0.35)
    topk = tiles.get("topk_per_channel", 60_000)
    cand_union = tiles["cand_union"]
    if cand_union is None:
        raise RuntimeError("build_nodes needs the in-memory candidate union from build_tiles")
    ys_all, xs_all = np.nonzero(cand_union)
    tid, _, _ = tile_index(valid.shape, tiles["tile_px"])
    t_at_node = tid[ys_all, xs_all]
    node = {"row": ys_all.astype(np.int32), "col": xs_all.astype(np.int32),
            "tile": t_at_node.astype(np.int32)}
    for spec in CHANNELS:
        d = _channel_lines(spec, valid, sigma_tensor_m, coh_gate, persist_gate, allowed, topk)
        node[f"coh_{spec.key}"] = d["coh"][ys_all, xs_all].astype(np.float32)
        node[f"persist_{spec.key}"] = d["persist"][ys_all, xs_all].astype(np.float32)
        node[f"strength_{spec.key}"] = d["strength"][ys_all, xs_all].astype(np.float32)
        node[f"theta_{spec.key}"] = tiles["per_channel"][spec.key]["theta"][t_at_node].astype(np.float32)
        node[f"tileR_{spec.key}"] = tiles["per_channel"][spec.key]["R"][t_at_node].astype(np.float32)
        del d
        log(f"  [pass 2] {spec.key:14s} node evidence extracted")
    cover = read_channel(ChannelSpec("depth_to_base", OFFICIAL, 15, "subsurface",
                                     "thickness of sedimentary cover"), valid)
    cover_rank = np.nan_to_num(T_rank01(cover, valid), nan=0.5)
    node["cover_rank"] = cover_rank[ys_all, xs_all].astype(np.float32)
    del cover, cover_rank
    np.savez_compressed(out / "nodes.npz", **node)
    log(f"wrote {out / 'nodes.npz'} ({ys_all.size} candidates)")
    return node


def build(work_dir: str = "work/dicoincidence", sigma_tensor_m: float = 300.0,
          tile_px: int = TILE_PX, n_perm: int = 400, topk_per_channel: int = 60_000,
          coh_gate: float = 0.30, persist_gate: float = 0.35, seed: int = 0,
          log=print) -> dict:
    """Run the whole detector and persist node features + the coincidence evidence.

    Memory strategy, stated because the first version of this function died here: the competition
    grid is 12.3 Mpix, so *one* full-grid float32 array is 49 MB and a channel needs about eight of
    them.  Pass 1 therefore keeps only candidates and per-tile azimuths, and pass 2 re-reads each
    channel to extract its values **at the node coordinates only**.  Recomputing the tensor costs
    ~4 minutes and saves ~2.3 GB, which on this box is the difference between a table and an
    out-of-memory kill.

    Steps, in order, with the reason each one is where it is:

    1. **Candidates (pass 1).** Every channel's structure tensor is reduced to ``line_strength``
       (coherence x along-strike persistence x energy rank) and its local maxima are candidates.  The
       candidate set is deliberately *blind*: top ``topk_per_channel`` per channel, no truth involved.
    2. **Tile azimuths.** Each channel's azimuth field becomes one azimuth per 1.6 km tile.
    3. **Coincidence.** Every family-disjoint channel pair gets a permutation test.
    4. **Node evidence (pass 2).** Each candidate reads off, per channel, its own coherence /
       persistence / strength and the azimuth of its tile; :func:`arm_scores` combines that evidence.
    5. Persist ``nodes.npz`` and ``evidence/dicoincidence.json``.
    """
    tiles = build_tiles(work_dir=work_dir, sigma_tensor_m=sigma_tensor_m, tile_px=tile_px,
                        topk_per_channel=topk_per_channel, coh_gate=coh_gate,
                        persist_gate=persist_gate, log=log)
    pairs, pm = coincidence_table(tiles, n_perm=n_perm, seed=seed, log=log)
    node = build_nodes(tiles, pairs, work_dir=work_dir, n_perm=n_perm, seed=seed, log=log)
    arms, meta = arm_scores(node, pairs, p_crit=0.05 / max(len(pairs), 1), z_gate=pm["z_gate"])
    node_scores = {k: v for k, v in arms.items()}
    np.savez_compressed(Path(work_dir) / "arms.npz",
                        **{k: v.astype(np.float32) for k, v in node_scores.items()})
    ev = {
        "what": "H53-1 cross-dataset orientation coincidence, permutation-calibrated",
        "tile_px": tile_px, "tile_km": tile_px * PIXEL_M / 1000.0,
        "sigma_tensor_m": sigma_tensor_m, "n_perm": n_perm, "seed": seed,
        "coh_gate": coh_gate, "persist_gate": persist_gate, "topk_per_channel": topk_per_channel,
        "candidate_union_px": int(tiles["cand_union"].sum()),
        "channels": [{"key": c.key, "path": c.path, "band": c.band, "family": c.family,
                      "physical": c.physical,
                      "n_candidates": tiles["per_channel"][c.key]["n_candidates"],
                      "tiles_with_azimuth": int(np.isfinite(
                          tiles["per_channel"][c.key]["theta"]).sum())}
                     for c in CHANNELS],
        "coincidence_pairs": pairs, "p_bonferroni": 0.05 / max(len(pairs), 1),
        "z_gate": pm["z_gate"], "arm_meta": meta,
    }
    (Path("evidence") / "dicoincidence.json").write_text(json.dumps(ev, indent=1, default=str))
    log(f"wrote {Path(work_dir) / 'arms.npz'} and evidence/dicoincidence.json")
    return ev


# ------------------------------------------------------------------------------------------------
# the arms
# ------------------------------------------------------------------------------------------------

def z_threshold(n_pairs: int, alpha: float = 0.05) -> float:
    """Two-sided normal threshold for ``alpha`` split over ``n_pairs`` -- a Bonferroni z, not a rune.

    The permutation test's own p-value cannot resolve below ``1/(n_perm+1)`` (0.0025 at 400 draws), so
    a Bonferroni p-gate over 100 pairs (0.0005) is *unreachable by construction* and would reject every
    pair for a reason that has nothing to do with the geology.  The z-score has no such floor, so it is
    the gate and the permutation p is reported next to it as a resolution-limited cross-check.
    """
    from math import sqrt
    from scipy.stats import norm
    if n_pairs <= 0:
        return float("inf")
    return float(norm.isf(alpha / (2.0 * n_pairs)))


def arm_scores(node: dict, pairs: list[dict], pct_by_pair: dict, z_gate: float | None = None,
               agree_deg: float = 22.5, tile_pct_gate: float = 0.90,
               surface_pct: float = 50.0) -> tuple[dict, dict]:
    """Per-node arm scores from **fabric-relative** coincidence evidence.

    The first version of this function gated on each pair's *global* z and on the local strike
    agreement, and it was useless: 37 of 100 pairs clear the global gate, so 93 % of candidate nodes
    counted as "corroborated" and 99.9 % as "A-corr".  The reason is geological, not statistical -- the
    whole province shares one N-S fabric, so two datasets agreeing in strike is the *default* here, not
    the exception.  The informative statement is therefore **relative to that pair's own behaviour**:
    a tile counts only when its agreement is unusual for *this pair* (``z_tile`` against the rolled
    null, which preserves the fabric), and a node counts only when its own tile is one of those.

    Definitions, all stated rather than tuned:

    * ``agree``    - the node's tile azimuths for two channels are within ``agree_deg`` (default 22.5,
      one eighth of the axial circle: the coarsest bin at which a 12-bin description is meaningful).
    * ``unusual``  - that tile sits in the top ``1 - tile_pct_gate`` (default top 10 %) of **this
      pair's own** tile-agreement distribution.  A per-tile *z-score* was tried first and is
      unreachable at this sample size: one tile contributes one scalar with a null s.d. of ~0.3, so
      |z| >= 3 would need cos2 >= 0.9 and fires on 0.0 % of tiles (measured), i.e. the gate would have
      been a silent no-op.  The percentile gate needs no variance estimate and its false-positive rate
      is the quantile itself, by construction.
    * ``B_corr``   - a surface channel (View B) with >= 1 field-family channel that is both ``agree``
      and ``unusual``.  "B confident, and independent physics corroborate *this place*."
    * ``A_corr``   - a node where >= 2 distinct **families** (magnetics/gravity/conductivity/
      radiometric/upward-continued-magnetics) are mutually ``agree`` and ``unusual`` *while the surface
      view is featureless here* (its own strength is below the ``surface_pct`` percentile of the node
      population, or its tile has no resolvable surface azimuth).  This is the brief's buried class.
    * ``B_only``   - a surface line with no corroboration at all: the suspect class (roads, levees,
      erosion), kept in the table so its measured value can be compared rather than asserted away.
    * ``union``    - every candidate, unweighted: the "no discovery logic" control on the same set.
    """
    keys = [k[len("theta_"):] for k in node if k.startswith("theta_")]
    surface = [k for k in keys if k in SURFACE_KEYS]
    field = [k for k in keys if k not in SURFACE_KEYS]
    fam_of: dict[str, str] = {}
    for k in keys:
        if k in surface:
            fam_of[k] = "surface"
    for p in pairs:
        fam_of[p["a"]] = p["family_a"]
        fam_of[p["b"]] = p["family_b"]
    cos_crit = float(np.cos(2.0 * np.deg2rad(agree_deg)))
    n = node["row"].size
    theta = {k: node[f"theta_{k}"] for k in keys}
    strength = {k: np.nan_to_num(node[f"strength_{k}"], nan=0.0) for k in keys}

    def pairwise_flag(k: str, r: str) -> np.ndarray:
        """Boolean per node: channels k and r agree *and* the agreement is unusual for this pair."""
        pmap = pct_by_pair.get((k, r))
        if pmap is None:
            pmap = pct_by_pair.get((r, k))
        if pmap is None:
            return np.zeros(n, dtype=bool)
        ta, tb = theta[k], theta[r]
        ok = np.isfinite(ta) & np.isfinite(tb)
        pct = pmap[node["tile"]]
        flag = np.zeros(n, dtype=bool)
        flag[ok] = np.cos(2.0 * A.axial_difference(ta[ok], tb[ok])) >= cos_crit
        return flag & np.isfinite(pct) & (pct >= tile_pct_gate)

    # per-channel corroboration counts (over channels of *different* families)
    corr_cnt = {}
    for k in keys:
        cnt = np.zeros(n, dtype=np.int32)
        for r in keys:
            if r == k or fam_of.get(r) == fam_of.get(k):
                continue
            cnt += pairwise_flag(k, r).astype(np.int32)
        corr_cnt[k] = cnt
    surf_strength = (np.maximum.reduce([strength[k] for k in surface]) if surface
                     else np.zeros(n))
    b_corr_cnt = (np.maximum.reduce([corr_cnt[k] for k in surface]) if surface
                  else np.zeros(n, dtype=np.int32))

    # families mutually agreeing, for the A-corr (buried) class
    fam_agree = {}
    for k in field:
        cnt = np.zeros(n, dtype=np.int32)
        for r in field:
            if r == k or fam_of.get(r) == fam_of.get(k):
                continue
            cnt += pairwise_flag(k, r).astype(np.int32)
        fam_agree[k] = cnt
    a_support = np.maximum.reduce(list(fam_agree.values())) if fam_agree else np.zeros(n, dtype=np.int32)
    a_families = np.zeros(n, dtype=np.int32)
    for k in field:
        a_families += (fam_agree[k] > 0).astype(np.int32)

    surf_thr = float(np.percentile(surf_strength, surface_pct))
    surface_featureless = (surf_strength <= surf_thr)
    for k in surface:
        surface_featureless |= ~np.isfinite(theta[k])
    cover = np.nan_to_num(node["cover_rank"], nan=0.0)
    arms = {
        "B_corr": np.where(b_corr_cnt > 0, surf_strength * (1.0 + b_corr_cnt), 0.0),
        "A_corr": np.where((a_families >= 2) & surface_featureless,
                           1.0 + np.minimum(a_support, 5) + cover, 0.0),
        "A_corr_deep": np.where((a_families >= 2) & surface_featureless & (cover >= 0.6),
                                2.0 + np.minimum(a_support, 5), 0.0),
        "B_only": np.where(b_corr_cnt == 0, surf_strength, 0.0),
        "union": np.maximum(surf_strength,
                            (np.maximum.reduce([strength[k] for k in field]) if field
                             else surf_strength)),
        "field_only": (np.maximum.reduce([strength[k] for k in field]) if field
                       else np.zeros(n)),
    }
    meta = {"n_surface_channels": len(surface), "n_field_channels": len(field),
            "n_pairs": len(pairs), "tile_pct_gate": tile_pct_gate, "agree_deg": agree_deg,
            "surface_strength_threshold": surf_thr,
            "z_gate_global_for_reference": z_gate,
            "share_b_corr": float((b_corr_cnt > 0).mean()),
            "share_a_corr": float(((a_families >= 2) & surface_featureless).mean()),
            "share_a_corr_deep": float(((a_families >= 2) & surface_featureless & (cover >= 0.6)).mean()),
            "share_featureless": float(surface_featureless.mean()),
            "b_corr_counts": {int(k): float((b_corr_cnt >= k).mean()) for k in (1, 2, 3)},
            "a_family_counts": {int(k): float((a_families >= k).mean()) for k in (1, 2, 3, 4)}}
    return arms, meta

# ----------------------------------------------------------------------------------------------
# the detector
# ----------------------------------------------------------------------------------------------

def _channel_lines(spec: ChannelSpec, valid: np.ndarray, sigma_tensor_m: float,
                   coh_gate: float, persist_gate: float, allowed: np.ndarray,
                   topk: int) -> dict:
    """One channel -> candidates, per-pixel line strength, and tile azimuths (pass 1 + pass 2).

    Returned arrays are either full-grid (``strength``, used once and dropped) or per-tile; the
    per-node extraction happens in :func:`build`, after the candidate union is known, so no per-channel
    full-grid arrays are ever held for more than one channel at a time.
    """
    a = read_channel(spec, valid)
    st = S.structure_tensor(a, valid, sigma_tensor_m=sigma_tensor_m)
    del a
    persist = S.oriented_line_energy(st["azimuth"], valid, sigma_m=sigma_tensor_m)
    coh = np.nan_to_num(st["coherence"], nan=0.0)
    per = np.nan_to_num(persist, nan=0.0)
    e_rank = np.nan_to_num(T_rank01(st["energy"], valid), nan=0.0).astype(np.float32)
    strength = (coh * per * e_rank).astype(np.float32)
    gate = allowed & (st["coherence"] > coh_gate) & (persist > persist_gate)
    cand = ND.local_maxima(np.where(gate, strength, 0.0), gate, radius_px=1)
    if int(cand.sum()) > topk:
        cand = ND.top_k_mask(strength, cand, topk)
    return {"cand": cand, "strength": strength, "coh": coh, "persist": per,
            "azimuth": st["azimuth"], "energy": st["energy"]}


def build_tiles(work_dir: str = "work/dicoincidence", sigma_tensor_m: float = 300.0,
                tile_px: int = TILE_PX, topk_per_channel: int = 60_000, coh_gate: float = 0.30,
                persist_gate: float = 0.35, log=print) -> dict:
    """Pass 1: candidates per channel + tile azimuths.  ~2 minutes, ~350 MB, writes tiles.npz.

    Staged on purpose: the permutation test and the arm rules are where the *thinking* changes and the
    tensors are where the *time* goes, so the expensive half is cached and only the cheap half re-runs
    when a statistic is corrected.  A single end-to-end function was rewritten five times in one
    session otherwise.
    """
    out = Path(work_dir)
    out.mkdir(parents=True, exist_ok=True)
    valid = footprint()
    cat = catalogue()
    allowed = valid & ~cat
    tid, _, tile_shape = tile_index(valid.shape, tile_px)
    n_tiles = int(tile_shape[0] * tile_shape[1])
    log(f"footprint {int(valid.sum())} px, catalogue {int(cat.sum())} px, "
        f"tiles {tile_shape[0]}x{tile_shape[1]} ({tile_px} px = {tile_px * PIXEL_M / 1000:.1f} km)")

    per_channel: dict[str, dict] = {}
    cand_union = np.zeros(valid.shape, dtype=bool)
    for spec in CHANNELS:
        d = _channel_lines(spec, valid, sigma_tensor_m, coh_gate, persist_gate, allowed,
                           topk_per_channel)
        n_cand = int(d["cand"].sum())
        cand_union |= d["cand"]
        theta_t, r_t, mass_t = tile_azimuth(d["azimuth"], d["coh"] * d["persist"], tid, n_tiles)
        per_channel[spec.key] = {"spec": spec, "theta": theta_t, "R": r_t, "mass": mass_t,
                                 "n_candidates": n_cand}
        log(f"  [pass 1] {spec.key:14s} family={spec.family:12s} candidates {n_cand:>7d}, "
            f"tiles with a resolvable azimuth {int(np.isfinite(theta_t).sum()):>6d}/{n_tiles}")
        del d
    log(f"candidate union: {int(cand_union.sum())} px")
    if not cand_union.any():
        raise RuntimeError("no candidates: thresholds are impossible on this data")
    np.savez_compressed(out / "tiles.npz",
                        tile_shape=np.array(tile_shape, dtype=np.int64),
                        candidate_px=np.array(cand_union.sum(), dtype=np.int64),
                        **{f"{k}__{f}": v for k, d in per_channel.items()
                           for f, v in (("theta", d["theta"]), ("R", d["R"]), ("mass", d["mass"]))},
                        **{f"ncand__{k}": np.array(d["n_candidates"], dtype=np.int64)
                           for k, d in per_channel.items()})
    return {"per_channel": per_channel, "tile_shape": tile_shape, "n_tiles": n_tiles,
            "cand_union": cand_union, "tile_px": tile_px, "sigma_tensor_m": sigma_tensor_m,
            "coh_gate": coh_gate, "persist_gate": persist_gate,
            "topk_per_channel": topk_per_channel}


def load_tiles(work_dir: str = "work/dicoincidence") -> dict:
    """Rebuild the pass-1 dict from ``tiles.npz`` without touching a raster."""
    z = np.load(Path(work_dir) / "tiles.npz")
    tile_shape = tuple(int(v) for v in z["tile_shape"])
    per_channel = {}
    for spec in CHANNELS:
        per_channel[spec.key] = {
            "spec": spec, "theta": z[f"{spec.key}__theta"], "R": z[f"{spec.key}__R"],
            "mass": z[f"{spec.key}__mass"], "n_candidates": int(z[f"ncand__{spec.key}"]),
        }
    return {"per_channel": per_channel, "tile_shape": tile_shape,
            "n_tiles": int(tile_shape[0] * tile_shape[1]),
            "candidate_px": int(z["candidate_px"]),
            "cand_union": None}


def agreement_percentile(cos2_tile: np.ndarray) -> np.ndarray:
    """Rank each tile's observed agreement within its own pair's tile population, in [0, 1].

    Distribution-free on purpose: it says "this tile agrees better than 90 % of the tiles this pair can
    be measured on", which needs no variance estimate and is therefore robust to the strong spatial
    autocorrelation that makes a per-tile z-score meaningless (neighbouring tiles are not independent
    samples of the same pair).
    """
    c = np.asarray(cos2_tile, dtype=np.float64)
    out = np.full(c.shape, np.nan)
    fin = np.isfinite(c)
    n = int(fin.sum())
    if n == 0:
        return out
    from scipy.stats import rankdata
    out[fin] = rankdata(c[fin], method="average") / n
    return out


def coincidence_table(tiles: dict, n_perm: int = 400, seed: int = 0, log=print) -> tuple[list, dict]:
    """Pass 2a: the family-disjoint permutation tests.  Cheap; re-run whenever a statistic changes."""
    per_channel = tiles["per_channel"]
    tile_shape = tiles["tile_shape"]
    keys = [c.key for c in CHANNELS]
    pairs, z_by_pair, pct_by_pair = [], {}, {}
    for i, ki in enumerate(keys):
        for kj in keys[i + 1:]:
            fi, fj = per_channel[ki]["spec"].family, per_channel[kj]["spec"].family
            if fi == fj:
                continue
            res, z_tile, cos2_tile = coincidence_test(per_channel[ki]["theta"],
                                                      per_channel[kj]["theta"],
                                                      tile_shape, n_perm=n_perm, seed=seed)
            if not res["usable"]:
                continue
            fin = np.isfinite(z_tile)
            res.update({"a": ki, "b": kj, "family_a": fi, "family_b": fj,
                        "tile_z_share_ge3": float((z_tile[fin] >= 3.0).mean()) if fin.any() else None,
                        "tile_z_share_le_m3": float((z_tile[fin] <= -3.0).mean()) if fin.any() else None})
            # flattened to the same row-major tile order tile_index() hands to the nodes; a 2-D map
            # indexed by a flat tile id silently reads the wrong tile (or raises) -- it raised.
            z_by_pair[(ki, kj)] = np.asarray(z_tile).reshape(-1)
            pct_by_pair[(ki, kj)] = agreement_percentile(cos2_tile).reshape(-1)
            pairs.append(res)
    pairs.sort(key=lambda r: r["p"])
    zt = z_threshold(len(pairs))
    if pairs:
        log(f"coincidence pairs tested: {len(pairs)} (family-disjoint); best: {pairs[0]['a']} vs "
            f"{pairs[0]['b']} obs {pairs[0]['obs']:+.3f}, null {pairs[0]['null_mean']:+.4f} "
            f"+- {pairs[0]['null_sd']:.4f}, z {pairs[0]['z']:+.1f}, p {pairs[0]['p']:.4f}")
    log(f"pairs clearing the Bonferroni z gate (|z| >= {zt:.2f}): "
        f"{sum(1 for p in pairs if p['z'] >= zt)} of {len(pairs)}")
    return pairs, {"z_gate": zt, "z_by_pair": z_by_pair, "pct_by_pair": pct_by_pair}


def build_nodes(tiles: dict, pairs: list, work_dir: str = "work/dicoincidence",
                n_perm: int = 400, seed: int = 0, log=print) -> dict:
    """Pass 2b: per-node evidence for every channel, written to nodes.npz."""
    out = Path(work_dir)
    valid = footprint()
    allowed = valid & ~catalogue()
    sigma_tensor_m = tiles.get("sigma_tensor_m", 300.0)
    coh_gate, persist_gate = tiles.get("coh_gate", 0.30), tiles.get("persist_gate", 0.35)
    topk = tiles.get("topk_per_channel", 60_000)
    cand_union = tiles["cand_union"]
    if cand_union is None:
        raise RuntimeError("build_nodes needs the in-memory candidate union from build_tiles")
    ys_all, xs_all = np.nonzero(cand_union)
    tid, _, _ = tile_index(valid.shape, tiles["tile_px"])
    t_at_node = tid[ys_all, xs_all]
    node = {"row": ys_all.astype(np.int32), "col": xs_all.astype(np.int32),
            "tile": t_at_node.astype(np.int32)}
    for spec in CHANNELS:
        d = _channel_lines(spec, valid, sigma_tensor_m, coh_gate, persist_gate, allowed, topk)
        node[f"coh_{spec.key}"] = d["coh"][ys_all, xs_all].astype(np.float32)
        node[f"persist_{spec.key}"] = d["persist"][ys_all, xs_all].astype(np.float32)
        node[f"strength_{spec.key}"] = d["strength"][ys_all, xs_all].astype(np.float32)
        node[f"theta_{spec.key}"] = tiles["per_channel"][spec.key]["theta"][t_at_node].astype(np.float32)
        node[f"tileR_{spec.key}"] = tiles["per_channel"][spec.key]["R"][t_at_node].astype(np.float32)
        del d
        log(f"  [pass 2] {spec.key:14s} node evidence extracted")
    cover = read_channel(ChannelSpec("depth_to_base", OFFICIAL, 15, "subsurface",
                                     "thickness of sedimentary cover"), valid)
    cover_rank = np.nan_to_num(T_rank01(cover, valid), nan=0.5)
    node["cover_rank"] = cover_rank[ys_all, xs_all].astype(np.float32)
    del cover, cover_rank
    np.savez_compressed(out / "nodes.npz", **node)
    log(f"wrote {out / 'nodes.npz'} ({ys_all.size} candidates)")
    return node


def build(work_dir: str = "work/dicoincidence", sigma_tensor_m: float = 300.0,
          tile_px: int = TILE_PX, n_perm: int = 400, topk_per_channel: int = 60_000,
          coh_gate: float = 0.30, persist_gate: float = 0.35, seed: int = 0,
          log=print) -> dict:
    """Run the whole detector and persist node features + the coincidence evidence.

    Memory strategy, stated because the first version of this function died here: the competition
    grid is 12.3 Mpix, so *one* full-grid float32 array is 49 MB and a channel needs about eight of
    them.  Pass 1 therefore keeps only candidates and per-tile azimuths, and pass 2 re-reads each
    channel to extract its values **at the node coordinates only**.  Recomputing the tensor costs
    ~4 minutes and saves ~2.3 GB, which on this box is the difference between a table and an
    out-of-memory kill.

    Steps, in order, with the reason each one is where it is:

    1. **Candidates (pass 1).** Every channel's structure tensor is reduced to ``line_strength``
       (coherence x along-strike persistence x energy rank) and its local maxima are candidates.  The
       candidate set is deliberately *blind*: top ``topk_per_channel`` per channel, no truth involved.
    2. **Tile azimuths.** Each channel's azimuth field becomes one azimuth per 1.6 km tile.
    3. **Coincidence.** Every family-disjoint channel pair gets a permutation test.
    4. **Node evidence (pass 2).** Each candidate reads off, per channel, its own coherence /
       persistence / strength and the azimuth of its tile; :func:`arm_scores` combines that evidence.
    5. Persist ``nodes.npz`` and ``evidence/dicoincidence.json``.
    """
    tiles = build_tiles(work_dir=work_dir, sigma_tensor_m=sigma_tensor_m, tile_px=tile_px,
                        topk_per_channel=topk_per_channel, coh_gate=coh_gate,
                        persist_gate=persist_gate, log=log)
    pairs, pm = coincidence_table(tiles, n_perm=n_perm, seed=seed, log=log)
    node = build_nodes(tiles, pairs, work_dir=work_dir, n_perm=n_perm, seed=seed, log=log)
    arms, meta = arm_scores(node, pairs, p_crit=0.05 / max(len(pairs), 1), z_gate=pm["z_gate"])
    node_scores = {k: v for k, v in arms.items()}
    np.savez_compressed(Path(work_dir) / "arms.npz",
                        **{k: v.astype(np.float32) for k, v in node_scores.items()})
    ev = {
        "what": "H53-1 cross-dataset orientation coincidence, permutation-calibrated",
        "tile_px": tile_px, "tile_km": tile_px * PIXEL_M / 1000.0,
        "sigma_tensor_m": sigma_tensor_m, "n_perm": n_perm, "seed": seed,
        "coh_gate": coh_gate, "persist_gate": persist_gate, "topk_per_channel": topk_per_channel,
        "candidate_union_px": int(tiles["cand_union"].sum()),
        "channels": [{"key": c.key, "path": c.path, "band": c.band, "family": c.family,
                      "physical": c.physical,
                      "n_candidates": tiles["per_channel"][c.key]["n_candidates"],
                      "tiles_with_azimuth": int(np.isfinite(
                          tiles["per_channel"][c.key]["theta"]).sum())}
                     for c in CHANNELS],
        "coincidence_pairs": pairs, "p_bonferroni": 0.05 / max(len(pairs), 1),
        "z_gate": pm["z_gate"], "arm_meta": meta,
    }
    (Path("evidence") / "dicoincidence.json").write_text(json.dumps(ev, indent=1, default=str))
    log(f"wrote {Path(work_dir) / 'arms.npz'} and evidence/dicoincidence.json")
    return ev
